### ISSUE TITLE
Voidling escape and fathomless voidling

### ISSUE THREAD

**Issue by ThyHeroBro** [FocusedFault/VoidlingRestored#1]
Hey, I'm not sure if you still have access or work on fathomless voidling and I couldn't find the github for it so I am unsure where else to put this. with voidling escape and fathomless voidling enabled, voidling will teleport underneath the stage during the escape sequence or his main boss fight constantly, I still want to fight a harder voidling but the teleport seems to ruin the fight, can you make it so the teleport ability is optional? because I would really like to disable it.
Thanks

**Comment by Nuxlar** [comment]
oh interesting, well I was going to redo fathomless at some point or include the rework in another mod so I'll close this for now, if the fathomless code isn't on Github I'm probably not going to revive the code for bug fixes if I'm going to redo it
